import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Campus Directory App",
  description: "Generated by create next app",
};

function NavBar() {
  return (
    <nav
      style={{ padding: "1rem" }}
      className="bg-gray-800 flex gap-15 justify-center"
    >
      <a href="/">Home</a>
      <a href="/students">Students</a>
      <a href="/faculty">Faculty</a>
    </nav>
  );
}

function Footer() {}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{}}
      >
        <NavBar />
        <main
          style={{ padding: "1rem", flex: 1 }}
          className="bg-white text-black dark:bg-gray-900 dark:text-white min-h-full"
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
